# Generated by Django 3.2.7 on 2021-09-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='eEmail',
            field=models.EmailField(max_length=254, unique='true'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='eFname',
            field=models.CharField(max_length=50, primary_key='true', serialize=False),
        ),
    ]
