# Generated by Django 3.2.7 on 2021-09-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20210911_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='eEmail',
            field=models.EmailField(max_length=254, primary_key='true', serialize=False, unique='true'),
        ),
    ]
